### ISSUE TITLE
Add Open Annotations vocabulary

### ISSUE THREAD

**Issue by darrenleeweber** [projecthydra-labs/rdf-vocab#36]
See also https://github.com/ruby-rdf/rdf/issues/169

The equivalent yaml for ` rdf-vocab/lib/rdf-vocab/config/vocab.yml` could be:

```
oa:
  class_name: OA
  uri: http://www.w3.org/ns/oa#
  source: http://www.openannotation.org/spec/core/20130208/oa.owl
```

Not entirely sure about the `StrictVocabulary' version, probably should be one of those 8-)
